using System.Diagnostics;

namespace websocket_forex_data_scrapper
{
    public class PythonRunner
    {
        private string _pythonPath = Path.GetDirectoryName(Environment.ProcessPath) + @"\..\..\..\ffc_scraper.py"; 


        public void RunPythonScript(string args = null)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "C:\\Users\\BangyanLi\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0"; // replace with your Python path
            start.Arguments = string.Format("\"{0}\" {1}", _pythonPath, args);
            start.UseShellExecute = false; // Do not use OS shell
            start.CreateNoWindow = true; // We don't need a new window
            start.RedirectStandardOutput = true; // Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back

            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string result = reader.ReadToEnd();
                    Console.Write(result);
                }
            }
        }

    }
}
