@websocket_forex_data_scrapper_HostAddress = http://localhost:5163

GET {{websocket_forex_data_scrapper_HostAddress}}/
Accept: application/json

###

GET {{websocket_forex_data_scrapper_HostAddress}}/
Accept: application/json

###
